from python:3.6

ADD requirements.txt /requirements.txt

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

ADD pythonPractice-0.11-py3-none-any.whl /pythonPractice-0.11-py3-none-any.whl

RUN pip3 install /pythonPractice-0.11-py3-none-any.whl





